export const ROUTE = {
  HOME: "/",
  LOGIN: "/connexion",
  FORGOT_PASSWORD: "/mot-de-passe-oublie",
  NEW_PASSWORD: "/nouveau-mot-de-passe",
  ALL_REPORTS: "/tous-les-signalements",
  NEW_REPORT_STEP_1: "/signalement?step=1",
  NEW_REPORT_STEP_2: "/signalement?step=2",
  NEW_REPORT_STEP_3: "/signalement?step=3",
  NEW_REPORT_STEP_4: "/signalement?step=4",
  REPORT: "/signalement",
  REPORT_WITH_ID: "/signalement/:id",
  HELP: "https://docs.aplus.beta.gouv.fr/",
  PROFILE: "/mon-profil",
  TEAMS: "/equipes",
  CREATE_TEAM: "/equipes/creer",
  USERS: "/utilisateurs",
  EDIT_USER: "/utilisateurs/modifier",
  CREATE_SUPERVISOR: "/utilisateurs/creer-un-superviseur",
  CONTACT: "/contact",
  FINISH_REGISTRATION: "/terminer-inscription",
  CGU: "/conditions-generales-d-utilisation",
  MENTIONS_LEGALES: "/mentions-legales",
  DONNEES_PERSONNELLES: "/politique-de-confidentialite",
  ACCESSIBILITE: "/accessibilite",
  PLAN_DU_SITE: "/plan-du-site",
  STATISTIQUES: "/statistiques",
  COMPLETE_PROFILE: "/profil-incomplet",
  VERIFY_2FA: "/verification-2fa",
  SETUP_2FA: "/configurer-2fa",
  ADMINISTRATION: "/administration",
  GOLDEN_DATASET: "/golden-dataset",
  GOLDEN_DATASET_RESULTS: "/golden-dataset/resultats",
};

export const SEARCH_PARAMS = {
  REPORT_CREATED: "report_created",
  FORM_EXPIRED: "form_expired",
} as const;
