export const STYLES = {
  container:
    "p-4 sm:p-8 md:p-12 lg:p-20 bg-white relative gap-4 flex flex-col mt-10",
  conversationsWrapper: "flex flex-col",
  authorBg: "bg-[#FEF6E3]",
  helperBg: "bg-[#F3F6FE]",
  instructorOnlyBg: "bg-[#F5F5F5]",
  messageContainer: "p-8 w-full",
  instructorNotice: " flex items-center gap-2",
  messageContent: "flex flex-col sm:flex-row gap-1 sm:gap-2 items-start",
  messageText: "mr-4 flex-1 min-w-0 m-0 p-0 whitespace-pre-wrap break-words",
  timestamp: "text-xs text-[#666666] whitespace-nowrap m-0 p-0 mt-1",
  filesContainer: "flex flex-col gap-2 mt-4",
  authorInfo: "flex items-center gap-4 mt-6",
  avatar: "w-14 h-14",
  authorName: "font-bold m-0 text-[#3A3A3A]",
  groupName: "m-0 text-[#3A3A3A]",
  statusEntryContainer: "relative pl-10 py-6 border-l border-[#E5E5E5]",
  statusMarker: "absolute left-[-9px] top-6 h-3 w-3 rounded-full bg-[#3558A2]",
  statusHeader: "flex flex-wrap items-center gap-2",
  statusLabel: "text-sm font-semibold text-[#3558A2]",
  statusTimestamp: "text-xs text-[#666666]",
  statusAuthor: "text-xs text-[#666666]",
  statusBadgeWrapper: "mt-3 w-fit",
} as const;
